import type { Metadata } from "next";
import "./globals.css";
import { ModalProvider } from "@/commons/providers/modal/modal.provider";
import { NextThemesProvider } from "@/commons/providers/next-themes/next-themes.provider";
import { ApolloClientProvider } from "@/commons/providers/apollo-client/apollo-client.provider";
import { Layout } from "@/commons/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextThemesProvider
          attribute="class"
          defaultTheme="system"
          enableSystem>
          <ApolloClientProvider>
            <ModalProvider>
              <Layout>{children}</Layout>
            </ModalProvider>
          </ApolloClientProvider>
        </NextThemesProvider>
      </body>
    </html>
  );
}
